Fix memtag.c for clang udpate
After clang update, we get below errors:

external/lk/arch/arm64/memtag.c:107:26: error: a function declaration without
a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
bool arch_tagging_enabled()
                         ^
                          void
external/lk/arch/arm64/memtag.c:112:29: error: a function declaration without
a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
bool arm64_tagging_supported()
                            ^
                             void

Bug: 269521171
Test: run trusty/vendor/google/aosp/scripts/build.py
Change-Id: I59da50be6c97c750099c41704ac51c51f1f3045f